apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: rook-ceph
spec:
  version: "{{ .TagName }}"
  homepage: https://github.com/rook/kubectl-rook-ceph
  shortDescription: "Rook plugin for Ceph management"
  description: |
     Krew plugin to provide insight to Rook configuration of the Ceph storage provider.
  platforms:
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - darwin
        - linux
        - windows
    {{addURIAndSha "https://github.com/rook/kubectl-rook-ceph/archive/{{ .TagName }}.zip" .TagName }}
    files:
    - from: "kubectl-rook-ceph-*/kubectl-rook-ceph.sh"
      to: "kubect-rook-ceph.sh"
    - from: "kubectl-rook-ceph-*/LICENSE"
      to: "."
    bin: kubect-rook-ceph.sh
