apiVersion: apps/v1
kind: Deployment
metadata:
  name: multus-validation-test-nginx
  labels:
    app: multus-validation-test-nginx
    app.kubernetes.io/name: "nginx"
    app.kubernetes.io/instance: "nginx" # there should only be one instance
    app.kubernetes.io/component: "server"
    app.kubernetes.io/part-of: "multus-validation-test"
    app.kubernetes.io/managed-by: "kubectl-rook-ceph"
spec:
  replicas: 1 # there should only be one instance
  selector:
    matchLabels:
      app: multus-validation-test-nginx
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: "{{ .multusNetworks }}"
      labels:
        app: multus-validation-test-nginx
    spec:
      # TODO: selectors, affinities, tolerations
      containers:
        - name: multus-validation-test-nginx
          image: nginx:stable-alpine
          resources: {}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: var-cache-nginx
              mountPath: /var/cache/nginx
            - name: server-conf
              mountPath: /etc/nginx/conf.d
            - name: var-run
              mountPath: /var/run
      volumes:
        - name: var-cache-nginx
          emptyDir: {}
        - name: server-conf
          configMap:
            name: multus-test-nginx-server-conf
        - name: var-run
          emptyDir: {}
