name: Plugin Go test
on:
  pull_request:

defaults:
  run:
    # reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
    shell: bash --noprofile --norc -eo pipefail -x {0}

jobs:
  with-krew:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: setup cluster
        uses: ./.github/workflows/cluster-setup
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: build the binary and run unit tests
        run: |
          make build
          sudo cp bin/kubectl-rook-ceph /usr/local/bin/kubectl-rook_ceph
          make test

      - name: Test plugin with ceph commands
        run: |
          set -e
          kubectl rook-ceph ceph status
          kubectl rook-ceph mons
          kubectl rook-ceph rbd ls replicapool

          POD=$(kubectl -n rook-ceph get pod -l app=rook-ceph-operator -o jsonpath="{.items[0].metadata.name}")
          kubectl rook-ceph operator restart
          # let's wait for operator pod to be restart
          kubectl -n rook-ceph wait --for=delete pod/$POD --timeout=100s
          tests/github-action-helper.sh wait_for_operator_pod_to_be_ready_state_default
          kubectl rook_ceph debug start rook-ceph-osd-0
          tests/github-action-helper.sh wait_for_deployment_to_be_running rook-ceph-osd-0-debug rook-ceph

          kubectl rook_ceph debug stop rook-ceph-osd-0
          tests/github-action-helper.sh wait_for_deployment_to_be_running rook-ceph-osd-0 rook-ceph
          kubectl rook-ceph operator set ROOK_LOG_LEVEL DEBUG
          kubectl rook-ceph rook version
          kubectl rook-ceph rook status
          kubectl rook-ceph rook status all
          kubectl rook-ceph rook status cephobjectstores
          kubectl rook-ceph rook purge-osd 0 --force
