name: Plugin Go test
on:
  pull_request:

defaults:
  run:
    # reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
    shell: bash --noprofile --norc -eo pipefail -x {0}

jobs:
  with-krew:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: setup cluster
        uses: ./.github/workflows/cluster-setup
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: build the binary and run unit tests
        run: |
          make build
          sudo cp bin/kubectl-rook-ceph /usr/local/bin/kubectl-rook_ceph
          make test

      - name: Test plugin with ceph commands
        run: |
          kubectl rook-ceph ceph status
          kubectl rook-ceph mons
          kubectl rook-ceph rbd ls replicapool
