name: Release Plugin
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  Release-Plugin-At-Krew-Index:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # krew-release-bot is a bot that automates the update of plugin manifests in krew-index when a new version of your kubectl plugin is released.
      # https://github.com/rajatjindal/krew-release-bot
      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.40
